name: nowave_map_poc
description: POC du fond marin NoWave, indépendant de l'application métier.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: 0.27.1
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
